# Generated by Django 2.1.5 on 2020-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
    ]
