# Generated by Django 2.1 on 2020-12-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='ID',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
