# Generated by Django 2.1 on 2020-12-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0002_auto_20201203_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='ID',
            new_name='User_ID',
        ),
    ]
